SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `frase` ;
CREATE SCHEMA IF NOT EXISTS `frase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `frase` ;

-- -----------------------------------------------------
-- Table `frase`.`frase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frase`.`frase` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `frase`.`frase` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `frase` TEXT NOT NULL ,
  `autor` VARCHAR(150) NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
